export const ADD_REVIEW_START = "ADD_REVIEW_START";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILURE = "ADD_REVIEW_FAILURE";

export const DELETE_REVIEW_START = "DELETE_REVIEW_START";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE";

//edit types
export const EDIT_REVIEW_START = "EDIT_REVIEW_START";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
export const EDIT_REVIEW_FAIL = "EDIT_REVIEW_FAIL";
export const GRAB_REVIEW = "GRAB_REVIEW";